name: llvm-memprof CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
 build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
    - name: Check disk space
      run: |
        df -h

    - name: Free disk space
      run: |
        set -euxo pipefail
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /usr/share/swift
        sudo rm -rf /usr/local/.ghcup
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        sudo apt-get clean
        df -h
    - name: Checkout (with submodules)
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Environment Setup
      shell: bash
      run: |
        set -euo pipefail
        ./init.sh --prebuilt-llvm
        source env.sh
        bazel --version

    - name: Generate Testdata
      shell: bash
      run: |
        set -euo pipefail
        source env.sh
        bash src/testdata/update_dwarf.sh

    - name: DwarfMetadata Fetcher Test
      run: |
        bazel run --cxxopt="-std=c++20" --crosstool_top=//toolchain:clang_suite //src:dwarf_metadata_fetcher_test --verbose_failures --sandbox_debug

    - name: Type Resolver Test
      run: |
        bazel run --cxxopt="-std=c++20" --crosstool_top=//toolchain:clang_suite //src:type_resolver_test --verbose_failures  --sandbox_debug
   
    - name: Histogram Builder Test
      run: |
        bazel run --cxxopt="-std=c++20" --crosstool_top=//toolchain:clang_suite //src:histogram_builder_test --verbose_failures  --sandbox_debug