name: llvm-memprof CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
 build:
    runs-on: ubuntu-20.04-64core
    strategy:
      fail-fast: true
    steps:
    - name: Checkout (with submodules)
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Build and Unit Tests
      shell: bash
      run: |
        set -euo pipefail
        ./init.sh
        source env.sh
        bazel --version
    - name: DwarfMetadata Fetcher Test
      run: |
        bazel run --cxxopt="-std=c++20" --crosstool_top=//toolchain:clang_suite //src:dwarf_metadata_fetcher_test --verbose_failures --sandbox_debug
  
    - name: Type Resolver Test
      run: |
        bazel run --cxxopt="-std=c++20" --crosstool_top=//toolchain:clang_suite //src:type_resolver_test --verbose_failures  --sandbox_debug
   
    - name: Histogram Builder Test
      run: |
        bazel run --cxxopt="-std=c++20" --crosstool_top=//toolchain:clang_suite //src:histogram_builder_test --verbose_failures  --sandbox_debug